language:
  python

services:
  - elasticsearch

python:
  - 3.6

install:
  - make install

script:
  - make test

before_script:
  - moto_server &
  - sleep 30
  - curl localhost:9200
  - curl localhost:5000

after_success:
  - coveralls
